const data = [
  {
    id: 1,
    title: 'Bahai',
    image: '/img/Mask1.png',
    category: 'Adventure trip',
    liked: true,
    price: '575.09',
  },
  {
    id: 2,
    title: 'Zürich',
    image: '/img/Mask2.png',
    category: 'Adventure trip',
    liked: false,
    price: '518.54',
  },
  {
    id: 3,
    title: 'Londolozi',
    image: '/img/Mask3.png',
    category: 'Mountain trip',
    liked: false,
    price: '185.3',
  },
  {
    id: 4,
    title: 'Ol Jogi Home',
    image: '/img/Mask4.png',
    category: 'Trip to the beach',
    liked: false,
    price: '984.05',
  },
  {
    id: 5,
    title: 'Los Cabos',
    image: '/img/Mask5.png',
    category: 'Camping trip',
    liked: false,
    price: '263.08',
  },
  {
    id: 6,
    title: 'Tarangire National Park',
    image: '/img/Mask6.png',
    category: 'Trip to the beach',
    liked: false,
    price: '682.29',
  },
  {
    id: 7,
    title: 'Dorado',
    image: '/img/Mask7.png',
    category: 'Trip to the beach',
    liked: false,
    price: '190.67',
  },
  {
    id: 8,
    title: 'Maldives',
    image: '/img/Mask8.png',
    category: 'Trip to the beach',
    liked: false,
    price: '275.02',
  },
  {
    id: 9,
    title: "Elewana Elsa's Kopje",
    image: '/img/Mask9.png',
    category: 'Adventure trip',
    liked: false,
    price: '155.54',
  },
  {
    id: 10,
    title: 'Okavango Delta',
    image: '/img/Mask10.png',
    category: 'Adventure trip',
    liked: false,
    price: '677.22',
  },
  {
    id: 11,
    title: 'Olare Orok',
    image: '/img/Mask11.png',
    category: 'Adventure trip',
    liked: false,
    price: '219.43',
  },
  {
    id: 12,
    title: 'Limerick',
    image: '/img/Mask12.png',
    category: 'Plane trip',
    liked: false,
    price: '346.96',
  },
];
export default data;

export const category = [
  { id: 1, title: 'Adventure trip' },
  { id: 2, title: 'Plane trip' },
  { id: 3, title: 'Trip to the beach' },
  { id: 4, title: 'Camping trip' },
  { id: 5, title: 'Mountain trip' },
];
